from pyrsistent import freeze

_STOPWORDS = {
    'en': {
        'a',
        "a's",
        'able',
        'about',
        'above',
        'according',
        'accordingly',
        'across',
        'actually',
        'after',
        'afterwards',
        'again',
        'against',
        "ain't",
        'all',
        'allow',
        'allows',
        'almost',
        'alone',
        'along',
        'already',
        'also',
        'although',
        'always',
        'am',
        'among',
        'amongst',
        'an',
        'and',
        'another',
        'any',
        'anybody',
        'anyhow',
        'anyone',
        'anything',
        'anyway',
        'anyways',
        'anywhere',
        'apart',
        'appear',
        'appreciate',
        'appropriate',
        'are',
        "aren't",
        'around',
        'as',
        'aside',
        'ask',
        'asking',
        'associated',
        'at',
        'available',
        'away',
        'awfully',
        'b',
        'be',
        'became',
        'because',
        'become',
        'becomes',
        'becoming',
        'been',
        'before',
        'beforehand',
        'behind',
        'being',
        'believe',
        'below',
        'beside',
        'besides',
        'best',
        'better',
        'between',
        'beyond',
        'both',
        'brief',
        'but',
        'by',
        'c',
        "c'mon",
        "c's",
        'came',
        'can',
        "can't",
        'cannot',
        'cant',
        'cause',
        'causes',
        'certain',
        'certainly',
        'changes',
        'clearly',
        'co',
        'com',
        'come',
        'comes',
        'concerning',
        'consequently',
        'consider',
        'considering',
        'contain',
        'containing',
        'contains',
        'corresponding',
        'could',
        "couldn't",
        'course',
        'currently',
        'd',
        'definitely',
        'described',
        'despite',
        'did',
        "didn't",
        'different',
        'do',
        'does',
        "doesn't",
        'doing',
        "don't",
        'done',
        'down',
        'downwards',
        'during',
        'e',
        'each',
        'edu',
        'eg',
        'eight',
        'either',
        'else',
        'even',
        'elsewhere',
        'enough',
        'entirely',
        'especially',
        'et',
        'etc',
        'even',
        'ever',
        'every',
        'everybody',
        'everyone',
        'everything',
        'everywhere',
        'ex',
        'exactly',
        'example',
        'except',
        'f',
        'far',
        'few',
        'fifth',
        'first',
        'five',
        'followed',
        'following',
        'follows',
        'for',
        'former',
        'formerly',
        'forth',
        'four',
        'from',
        'further',
        'furthermore',
        'g',
        'get',
        'gets',
        'getting',
        'given',
        'gives',
        'go',
        'goes',
        'going',
        'gone',
        'got',
        'gotten',
        'greetings',
        'h',
        'had',
        "hadn't",
        'happens',
        'hardly',
        'has',
        "hasn't",
        'have',
        "haven't",
        'having',
        'he',
        "he's",
        'hello',
        'help',
        'hence',
        'her',
        'here',
        "here's",
        'hereafter',
        'hereby',
        'herein',
        'hereupon',
        'hers',
        'herself',
        'hi',
        'him',
        'himself',
        'his',
        'hither',
        'hopefully',
        'how',
        'howbeit',
        'however',
        'i',
        "i'd",
        "i'll",
        "i'm",
        "i've",
        'ie',
        'if',
        'ignored',
        'immediate',
        'in',
        'inasmuch',
        'inc',
        'include',
        'including',
        'indeed',
        'indicate',
        'indicated',
        'indicates',
        'inner',
        'insofar',
        'instead',
        'into',
        'inward',
        'is',
        "isn't",
        'it',
        "it'd",
        "it'll",
        "it's",
        'its',
        'itself',
        'j',
        'just',
        'k',
        'keep',
        'keeps',
        'kept',
        'know',
        'knows',
        'known',
        'l',
        'last',
        'lately',
        'later',
        'latter',
        'latterly',
        'least',
        'less',
        'lest',
        'let',
        "let's",
        'like',
        'liked',
        'likely',
        'little',
        'look',
        'looking',
        'looks',
        'ltd',
        'm',
        'mainly',
        'many',
        'may',
        'maybe',
        'me',
        'mean',
        'meanwhile',
        'merely',
        'might',
        'more',
        'moreover',
        'most',
        'mostly',
        'much',
        'must',
        'my',
        'myself',
        'n',
        'name',
        'namely',
        'nd',
        'near',
        'nearly',
        'necessary',
        'need',
        'needs',
        'neither',
        'never',
        'nevertheless',
        'new',
        'next',
        'nine',
        'no',
        'nobody',
        'non',
        'none',
        'noone',
        'nor',
        'normally',
        'not',
        'nothing',
        'novel',
        'now',
        'nowhere',
        'o',
        'obviously',
        'of',
        'off',
        'often',
        'oh',
        'ok',
        'okay',
        'old',
        'on',
        'once',
        'one',
        'ones',
        'only',
        'onto',
        'or',
        'other',
        'others',
        'otherwise',
        'ought',
        'our',
        'ours',
        'ourselves',
        'out',
        'outside',
        'over',
        'overall',
        'own',
        'p',
        'page',
        'particular',
        'particularly',
        'per',
        'perhaps',
        'placed',
        'please',
        'plus',
        'possible',
        'presumably',
        'probably',
        'provides',
        'q',
        'que',
        'quite',
        'qv',
        'r',
        'rather',
        'rd',
        're',
        'really',
        'reasonably',
        'regarding',
        'regardless',
        'regards',
        'relatively',
        'respectively',
        'right',
        's',
        'said',
        'same',
        'saw',
        'say',
        'saying',
        'says',
        'second',
        'secondly',
        'see',
        'seeing',
        'seem',
        'seemed',
        'seeming',
        'seems',
        'seen',
        'self',
        'selves',
        'sensible',
        'sent',
        'serious',
        'seriously',
        'seven',
        'several',
        'shall',
        'she',
        'should',
        "shouldn't",
        'since',
        'six',
        'so',
        'some',
        'somebody',
        'somehow',
        'someone',
        'something',
        'sometime',
        'sometimes',
        'somewhat',
        'somewhere',
        'soon',
        'sorry',
        'specified',
        'specify',
        'specifying',
        'still',
        'sub',
        'such',
        'sup',
        'sure',
        't',
        "t's",
        'take',
        'taken',
        'tell',
        'tends',
        'th',
        'than',
        'thank',
        'thanks',
        'thanx',
        'that',
        "that's",
        'thats',
        'the',
        'their',
        'theirs',
        'them',
        'themselves',
        'then',
        'thence',
        'there',
        "there's",
        'thereafter',
        'thereby',
        'therefore',
        'therein',
        'theres',
        'thereupon',
        'these',
        'they',
        "they'd",
        "they'll",
        "they're",
        "they've",
        'think',
        'third',
        'this',
        'thorough',
        'thoroughly',
        'those',
        'though',
        'three',
        'through',
        'throughout',
        'thru',
        'thus',
        'to',
        'together',
        'too',
        'took',
        'toward',
        'towards',
        'tried',
        'tries',
        'truly',
        'try',
        'trying',
        'twice',
        'two',
        'u',
        'un',
        'under',
        'unfortunately',
        'unless',
        'unlikely',
        'until',
        'unto',
        'up',
        'upon',
        'us',
        'use',
        'used',
        'useful',
        'uses',
        'using',
        'usually',
        'uucp',
        'v',
        'value',
        'various',
        'very',
        'via',
        'viz',
        'vs',
        'want',
        'wants',
        'was',
        "wasn't",
        'way',
        'we',
        "we'd",
        "we'll",
        "we're",
        "we've",
        'website',
        'welcome',
        'well',
        'went',
        'were',
        "weren't",
        'what',
        "what's",
        'whatever',
        'when',
        'whence',
        'whenever',
        'where',
        "where's",
        'whereafter',
        'whereas',
        'whereby',
        'wherein',
        'whereupon',
        'wherever',
        'whether',
        'which',
        'while',
        'whither',
        'who',
        "who's",
        'whoever',
        'whole',
        'whom',
        'whose',
        'why',
        'will',
        'willing',
        'wish',
        'with',
        'within',
        'without',
        "won't",
        'would',
        'would',
        "wouldn't",
        'x',

        'yes',
        'yet',
        'you',
        "you'd",
        "you'll",
        "you're",
        "you've",
        'your',
        'yours',
        'yourself',
        'yourselves',
        'z',
        'zero',
        
        'a',
         'about',
         'above',
         'after',
         'again',
         'against',
         'ain',
         'all',
         'am',
         'an',
         'and',
         'any',
         'are',
         'aren',
         'arent',
         'as',
         'at',
         'be',
         'because',
         'been',
         'before',
         'being',
         'below',
         'between',
         'both',
         'but',
         'by',
         'can',
         'couldn',
         'couldnt',
         'd',
         'did',
         'didn',
         'didnt',
         'do',
         'does',
         'doesn',
         'doesnt',
         'doing',
         'don',
         'dont',
         'down',
         'during',
         'each',
         'few',
         'for',
         'from',
         'further',
         'had',
         'hadn',
         'hadnt',
         'has',
         'hasn',
         'hasnt',
         'have',
         'haven',
         'havent',
         'having',
         'he',
         'her',
         'here',
         'hers',
         'herself',
         'him',
         'himself',
         'his',
         'how',
         'i',
         'if',
         'in',
         'into',
         'is',
         'isn',
         'isnt',
         'it',
         'its',
         'itself',
         'just',
         'll',

         'ma',
         'me',
         'mightn',
         'mightnt',
         'more',
         'most',
         'mustn',
         'mustnt',
         'my',
         'myself',
         'needn',
         'neednt',
         'no',
         'nor',
         'not',
         'now',

         'of',
         'off',
         'on',
         'once',
         'only',
         'or',
         'other',
         'our',
         'ours',
         'ourselves',
         'out',
         'over',
         'own',
         're',
         'same',
         'shan',
         'shant',
         'she',
         'shes',
         'should',
         'shouldn',
         'shouldnt',
         'shouldve',
         'so',
         'some',
         'such',
         'than',
         'that',
         'thatll',
         'the',
         'their',
         'theirs',
         'them',
         'themselves',
         'then',
         'there',
         'these',
         'they',
         'this',
         'those',
         'through',
         'to',
         'too',
         'under',
         'until',
         'up',
         've',
         'very',
         'was',
         'wasn',
         'wasnt',
         'we',
         'were',
         'weren',
         'werent',
         'what',
         'when',
         'where',
         'which',
         'while',
         'who',
         'whom',
         'why',
         'will',
         'with',
         'won',
         'wont',
         'wouldn',
         'wouldnt',
         'you',
         'youd',
         'youll',
         'your',
         'youre',
         'yours',
         'yourself',
         'yourselves',
         'youve',
         "cant", 'cannot', 'fix', 'cant', 'never', 'slow', 'disable', 'unable'
    },
     'zh':{'必',
         #'造成',
         '對',
         '即使',
         '如此等等',
         '依靠',
         '剛才',
         '＞λ',
         '總是',
         '距',
         '暗中',
         '下列',
         '乒',
         'were',
         '哩度',
         #'見',
         'accordingly',
         '快要',
         '１２％',
         '不了',
         'back',
         '概',
         '嘩啦',
         '後',
         'see',
         'an',
         '來看',
         'regarding',
         'using',
         '能',
         'whole',
         '你是',
         '徹底',
         '所在',
         'below',
         '老大',
         '需要',
         '常言道',
         'between',
         'own',
         '窮年累月',
         '內',
         '正如',
         '強調',
         'their',
         '日臻',
         "shed",
         '係',
         '反倒',
         '不大',
         '突出',
         '當',
         'anything',
         'either',
         'end',
         '說明',
         "youll",
         '咧',
         'howbeit',
         '他人',
         '臭',
         '什麼',
         '寧可',
         '你的',
         'further',
         'nd',
         'thence',
         'until',
         '雖',
         '［④ｂ］',
         'th',
         '乎',
         '相同',
         '如上',
         'among',
         'theirs',
         'done',
         '沿著',
         '意思',
         '歟',
         'unfortunately',
         'reasonably',
         'exactly',
         'co',
         '而后',
         '好多',
         '並沒有',
         '您',
         '不問',
         '趁著',
         'ought',
         '立',
         '啊喲',
         '相對',
         '極端',
         '召開',
         'inward',
         '［①ｃ］',
         '?',
         'tried',
         '？',
         '特點',
         'than',
         '非徒',
         '此中',
         'sometimes',
         '可見',
         'therefore',
         '憑藉',
         '嘎登',
         '剛',
         '應該',
         '一何',
         'appear',
         '有時',
         'behind',
         '迅速',
         '嗰啲',
         '並不是',
         '不盡',
         '一旦',
         '就算',
         '余外',
         '繼之',
         '到底',
         '哈',
         '二話不說',
         '別處',
         '故',
         '獲得',
         '５',
         '歸',
         '除開',
         '而又',
         '各個',
         '呼啦',
         'allow',
         'unlike',
         'afterwards',
         'away',
         '己',
         '一啲',
         '格外',
         '自身',
         '此時',
         '大張旗鼓',
         'during',
         '不僅僅',
         '成年',
         '［⑤］',
         'been',
         '縱使',
         '拿',
         '矣哉',
         '及至',
         'ie',
         'which',
         '唄',
         '那般',
         '來自',
         '甚麼',
         '過來',
         '－－',
         'changes',
         'quite',
         '啐',
         '決定',
         '即若',
         '反應',
         '一.',
         'wants',
         '不怎麼',
         '我的',
         '這一來',
         '不可抗拒',
         'had',
         '幾番',
         '於是乎',
         '才能',
         '起',
         '返',
         '嗡嗡',
         'later',
         '即便',
         "thatve",
         '趕早不趕晚',
         'recently',
         '.',
         '以及',
         '據',
         'course',
         '倘若',
         '〕',
         '"',
         '歡迎',
         '乃至於',
         '其中',
         '隻要',
         "shant",
         '漫說',
         "werent",
         '各人',
         'especially',
         'inc',
         '哪邊',
         '如果',
         '已矣',
         '上去',
         '換句話說',
         '）÷（１－',
         '別',
         'contains',
         '指',
         'mean',
         '加強',
         '隻是',
         '分期分批',
         '但是',
         'very',
         'yours',
         '不亦樂乎',
         '中小',
         'necessary',
         '二來',
         'minus',
         '領域',
         'secondly',
         '為何',
         '近年來',
         '=',
         'according',
         '真是',
         '從早到晚',
         '曾',
         '廣大',
         '一片',
         "cmon",
         '下去',
         "whos",
         '反之亦然',
         '得天獨厚',
         '適當',
         '［①②］',
         '唉',
         'said',
         '..',
         '得起',
         'please',
         '哼唷',
         #'useful',
         'made',
         '〈',
         '大舉',
         '梗係',
         '頓時',
         '聯系',
         'till',
         '即',
         'cause',
         '隨著',
         '不能不',
         '打從',
         '鼓勵',
         '不是',
         '了解',
         '若非',
         '特殊',
         '至',
         '｛－',
         '溯',
         "darent",
         '任何',
         '奈',
         'doing',
         '基於',
         '逐步',
         'do',
         'gets',
         'still',
         '［②⑩］',
         'yourselves',
         '1',
         '在下',
         '從重',
         '>',
         '咳',
         '孰知',
         '或則',
         '豁然',
         '而後',
         'n',
         'everything',
         'right',
         '過於',
         '由是',
         '巴巴',
         '果真',
         'comes',
         '而論',
         'many',
         "theyve",
         '日漸',
         '恰恰',
         'tries',
         '遇到',
         'thanx',
         'thus',
         '頃刻',
         '趕快',
         'did',
         '至今',
         '焉',
         '出於',
         'these',
         '嗡',
         'anybody',
         'someone',
         '挨門挨戶',
         '起初',
         '豈止',
         '直到',
         '總而言之',
         '堅決',
         '［①Ｃ］',
         '亦',
         '［①⑧］',
         'three',
         '其它',
         '不滿',
         '或',
         'hereby',
         '的話',
         '鄙人',
         'mainly',
         '只',
         '哪樣',
         '自家',
         '積極',
         '砰',
         '*',
         '據我所知',
         '既',
         '同埋',
         '寧願',
         '以至於',
         'sometime',
         'p',
         '末##末',
         'themselves',
         '庶幾',
         'mine',
         '雲爾',
         '絕非',
         '即是說',
         '來著',
         '對待',
         '倒不如說',
         '故此',
         '+',
         '日',
         '如若',
         #'去',
         '今後',
         '偶爾',
         '多虧',
         '兮',
         '本',
         #'到',
         'even',
         '個人',
         'nevertheless',
         '［②ｆ］',
         '望',
         '大事',
         '佢',
         'getting',
         '下來',
         '起來',
         'here',
         #'不比',
         '－β',
         'in',
         '規則',
         '哩啲',
         '開始',
         '只係',
         '四',
         '盡管',
         '並沒',
         '這個',
         "maynt",
         'may',
         '以下',
         '願意',
         '［①⑤］',
         '２．３％',
         '可謂',
         '換言之',
         #'無法',
         '一份',
         '如下',
         '＝',
         '別的',
         'lest',
         '慣常',
         '設若',
         '借以',
         'j',
         '‘',
         '，',
         'kept',
         '出來',
         '嘿',
         '針對',
         '除去',
         '以來',
         '使得',
         'seeing',
         '～±',
         '不拘',
         #'本地',
         'becoming',
         #'廣泛',
         '屢次',
         '從頭',
         'different',
         '並且',
         '屢屢',
         '們',
         '［③ａ］',
         '［④ｃ］',
         '再者',
         'beside',
         '那麼些',
         'possible',
         '遵循',
         '這兒',
         'ourselves',
         '總結',
         '冒',
         'otherwise',
         '第二',
         '從不',
         '」',
         '宣布',
         '猛然',
         '常',
         '然而',
         '［⑧］',
         '自打',
         'ending',
         '接著',
         'ignored',
         '之所以',
         '沿',
         '盡快',
         'took',
         '每每',
         '＋',
         '多麼',
         '這麼些',
         '隻限',
         '進步',
         '老',
         'those',
         '復雜',
         '准備',
         '嘍',
         '不過',
         '［③①］',
         'x',
         'un',
         '幾度',
         '嘩',
         '動輒',
         '將要',
         '學習',
         '居然',
         '慢說',
         '＝☆',
         'found',
         '比照',
         '看出',
         '那麼',
         'selves',
         '［④ａ］',
         'following',
         'insofar',
         '不知不覺',
         'becomes',
         'everybody',
         '雙方',
         '借',
         '月',
         '轟然',
         '猛然間',
         '取得',
         '依',
         '基本',
         '應當',
         '關於',
         '哪裡',
         '千',
         '上面',
         '是的',
         'how',
         'itself',
         'whither',
         '同樣',
         '敢情',
         '以期',
         'indicated',
         '除卻',
         'within',
         'f',
         'wherever',
         "were",
         '別人',
         '可',
         '立即',
         '類',
         '與此同時',
         '嗎',
         '接連',
         'nobody',
         '得',
         '經常',
         '絕對',
         '4日',
         "lets",
         '高低',
         '從寬',
         '受到',
         '【',
         '呆呆地',
         '啪達',
         '［①⑨］',
         '問題',
         '－',
         '了',
         '直接',
         '（',
         'ever',
         'let',
         '二話沒說',
         '種',
         '哦',
         'appreciate',
         '由',
         'soon',
         'greetings',
         '一定',
         '待到',
         '或是',
         '瑟瑟',
         'novel',
         '該款',
         'et',
         'A',
         '不消',
         '串行',
         '保持',
         '照',
         '看上去',
         'willing',
         '8',
         '被',
         '到了兒',
         '規定',
         '庶乎',
         '＝－',
         '雖則',
         'always',
         '即如',
         '接連不斷',
         '密切',
         '多次',
         'nor',
         '到處',
         '噉',
         '說來',
         '２',
         '云爾',
         '不迭',
         're',
         'must',
         'herself',
         '匆匆',
         '為此',
         '故意',
         '甚或',
         'non',
         '她',
         '為什麼',
         '除此以外',
         '臨',
         'particular',
         '此外',
         '嘢',
         '況且',
         '且說',
         '甚而',
         '累次',
         '絕不',
         '人',
         '立地',
         'aside',
         '平素',
         'gone',
         '多',
         'unto',
         '可能',
         '之前',
         '不敢',
         '盡管如此',
         '大量',
         '藉以',
         '屢次三番',
         '不足',
         '如常',
         'six',
         'c',
         '堅持',
         '再則',
         'though',
         '反映',
         'often',
         'only',
         '今',
         '喔唷',
         '放量',
         '〕〔',
         '看到',
         '非常',
         '起頭',
         '不由得',
         '每當',
         '認為',
         '從而',
         'keep',
         '從輕',
         "youd",
         'some',
         '產品',
         'self',
         '各地',
         'what',
         '莫如',
         '構成',
         '哩樣',
         'seven',
         '［①ｄ］',
         '對方',
         '抑或',
         '盡早',
         '某些',
         '不再',
         '當著',
         '呸',
         'might',
         '大略',
         '那兒',
         '凡',
         '結果',
         '之',
         '挨次',
         '介於',
         '頂多',
         '沒有',
         '開立',
         '６',
         'definitely',
         '適用',
         'furthermore',
         '得到',
         '０：２',
         'ex',
         "theres",
         "youre",
         '切切',
         '說說',
         '極為',
         '迄',
         '按說',
         '話說',
         '憑',
         '親眼',
         '9日',
         '啊',
         'currently',
         '按照',
         '反之則',
         '哪年',
         'four',
         '應用',
         'almost',
         'rather',
         '乘機',
         '將近',
         '從',
         '頗',
         '更進一步',
         '繼而',
         '當前',
         '０',
         'inc.',
         '然後',
         '以前',
         '［＊］',
         '非獨',
         'this',
         '麼',
         '呀',
         '最高',
         'asking',
         "im",
         'make',
         '可好',
         '周圍',
         '你們',
         '何嘗',
         '原來',
         'shall',
         'think',
         '存心',
         '盡',
         '咦',
         '這般',
         '＝″',
         '些',
         '裡面',
         '要是',
         '哎',
         '［①Ａ］',
         'looks',
         'whoever',
         '親手',
         '按時',
         '迫於',
         'taking',
         '］［',
         'least',
         '大凡',
         'went',
         '充其量',
         '敢',
         'be',
         '不只',
         '嗬',
         '通過',
         '伙同',
         '在於',
         '傳',
         '據實',
         '繼后',
         'toward',
         'used',
         '依照',
         '到頭來',
         '變成',
         '［②］',
         'onto',
         'whereas',
         '靠',
         'yes',
         'elsewhere',
         '＜＜',
         '也好',
         '--',
         'truly',
         'its',
         'looking',
         '兩者',
         'nowhere',
         'knows',
         'although',
         "here's",
         '如期',
         'latter',
         '按期',
         '斷然',
         '湊巧',
         '要',
         '加上',
         'regards',
         "shell",
         '合理',
         '不免',
         '其后',
         '至若',
         'like',
         '此后',
         '首先',
         'z',
         '共總',
         '｝',
         '偏偏',
         '以至',
         '六',
         '１．',
         'clearly',
         '下面',
         'formerly',
         '一則',
         '中間',
         '哇',
         'ｃ］',
         '咱',
         '光是',
         '任憑',
         '替',
         '據悉',
         '另外',
         '採取',
         '［③Ｆ］',
         'we',
         '全力',
         'gives',
         '自從',
         'evermore',
         'for',
         '尚且',
         '啷噹',
         'thereafter',
         '恰巧',
         '尤其',
         '千萬',
         '歸齊',
         '莫',
         '啲',
         '而且',
         '還有',
         'indeed',
         '將才',
         '#',
         '叫',
         '吧噠',
         '上',
         '著',
         'whereafter',
         'd',
         '倘或',
         '點樣',
         '無寧',
         '＿',
         'no-one',
         '俺們',
         '人民',
         '多數',
         'v',
         '乘虛',
         '乃',
         '又及',
         'then',
         '而',
         '一起',
         '［⑤］］',
         '嗚呼',
         '方才',
         "wasnt",
         'considering',
         "ones",
         '既是',
         'appropriate',
         '古來',
         'thereby',
         'neither',
         'try',
         '何須',
         '看起來',
         'h',
         'his',
         'my',
         'begin',
         '彼',
         'actually',
         'thorough',
         'upwards',
         '真正',
         '另行',
         '徹夜',
         '由於',
         '［①Ｅ］',
         '總的來看',
         'merely',
         '理應',
         'about',
         '只消',
         '多年前',
         '當下',
         'nine',
         '豈但',
         'use',
         'has',
         '要麼',
         "wed",
         '如此',
         '朝著',
         '＆',
         '相當',
         '使用',
         '不管',
         'namely',
         '４',
         'w',
         ';',
         '或多或少',
         '4',
         '嘛',
         'old',
         '算是',
         '借此',
         '轉貼',
         'g',
         'nonetheless',
         '嚇',
         'l',
         '盡心竭力',
         '畢竟',
         '㈧',
         'backward',
         '嗯',
         'rd',
         'along',
         'entirely',
         '8日',
         'ＺＸＦＩＴＬ',
         '對比',
         '不光',
         '隻怕',
         '［③ｈ］',
         '當場',
         '上來',
         '權時',
         '能夠',
         '常言說',
         '＋＋',
         '6',
         '省得',
         'per',
         '［②④',
         '切不可',
         '讓',
         'through',
         '怎奈',
         '其餘',
         '的確',
         '這',
         "they're",
         '記者',
         '步調',
         '比起',
         '轉變',
         'get',
         '打開天窗說亮話',
         '跟',
         'instead',
         '反之',
         '攔腰',
         '不若',
         '組成',
         '嘔',
         '附近',
         'notwithstanding',
         '連',
         '時候',
         'become',
         '既往',
         '不已',
         '乜',
         'forth',
         '接下來',
         '恰如',
         '充其極',
         '除此而外',
         'associated',
         '爾後',
         'anywhere',
         "aint",
         "therell",
         '成年累月',
         '［②ｉ］',
         'hello',
         '之一',
         '為',
         '由此可見',
         '6日',
         '只有',
         'indicates',
         '每逢',
         '別說',
         'brief',
         '除了',
         'best',
         'by',
         '￥',
         '向著',
         '同一',
         '’',
         'every',
         '人人',
         '］∧′＝［',
         '隨時',
         '做到',
         '也',
         '另',
         'b',
         '至於',
         '簡言之',
         '現在',
         'adj',
         'one',
         'enough',
         '很少',
         '若夫',
         'undoing',
         '總的來說',
         '傳聞',
         "thatll",
         '［②②］',
         '倍加',
         'trying',
         '叮當',
         '剛巧',
         '不要',
         '大家',
         '從優',
         '不得不',
         'ｆ］',
         '姑且',
         '［②ａ］',
         '［④ｅ］',
         'makes',
         'mostly',
         'us',
         '方面',
         'because',
         '所幸',
         '容易',
         '之后',
         "wheres",
         '論',
         '全然',
         '初',
         'overall',
         'ours',
         'keeps',
         '從此',
         '掌握',
         '必定',
         "hell",
         'thereupon',
         'somewhat',
         'alongside',
         '看看',
         '邊',
         '\\',
         'hither',
         '反過來說',
         '敞開兒',
         '竟而',
         '便',
         '是',
         '截至',
         '以後',
         '多多',
         'another',
         'que',
         '分高額',
         'relatively',
         '擴大',
         '偉大',
         '往往',
         '抽冷子',
         '後面',
         '最近',
         '皆可',
         '不僅僅是',
         '元／噸',
         '開發者',
         '一下',
         '頃刻之間',
         '不惟',
         '相應',
         '越是',
         "whats",
         'hopefully',
         'say',
         '《',
         'once',
         '無',
         '實際',
         '鑒於',
         'without',
         '［①ａ］',
         '哪兒',
         '不成',
         '嘅',
         '從來',
         '哪天',
         '誰',
         '般的',
         '倒不如',
         '［③ｄ］',
         'each',
         '才',
         'corresponding',
         '加入',
         '歷',
         '矣乎',
         'when',
         "itll",
         'better',
         '盡心盡力',
         '心裡',
         '誠如',
         '舉凡',
         'first',
         ')',
         '噓',
         '寧',
         '莫不',
         '誰人',
         '是不是',
         '具體來說',
         '諗',
         '叫做',
         '略為',
         'other',
         '起首',
         '難怪',
         '形成',
         '后',
         '因著',
         '“',
         '加之',
         'got',
         '呢',
         '７',
         '0',
         '嘎',
         'sorry',
         '如上所述',
         '不得',
         '就是',
         'ＬＩ',
         'down',
         '更加',
         '老老實實',
         '請勿',
         '必要',
         '難得',
         '零',
         '－［＊］－',
         'already',
         '對應',
         'everywhere',
         "'",
         '不如',
         '因了',
         '暗自',
         '重大',
         '幾多',
         '比較',
         '7日',
         '仍然',
         '不管怎樣',
         '只怕',
         'r',
         '次第',
         'q',
         '存在',
         '嗰',
         "therere",
         '左右',
         '不斷',
         'neverf',
         '他們',
         '—',
         '一個',
         '之類',
         '”',
         '哉',
         '全身心',
         '確定',
         '難道說',
         'known',
         '決非',
         '一面',
         "ive",
         '目前',
         '某',
         'amongst',
         '為了',
         '屬於',
         '不論',
         "havent",
         '沙沙',
         '卻不',
         'u',
         '怎麼樣',
         '各級',
         '不常',
         '充分',
         '後來',
         '相信',
         'whichever',
         'to',
         '_',
         '呼哧',
         '進而',
         '哎喲',
         '弗',
         '取道',
         '譬喻',
         '不擇手段',
         'wonder',
         '［①④］',
         'same',
         '［⑩］',
         '者',
         '該當',
         '乘勢',
         '不巧',
         '一一',
         '不盡然',
         '［⑤ｅ］',
         'hundred',
         '並排',
         'off',
         'thru',
         '昂然',
         '烏乎',
         'as',
         '一番',
         'seen',
         '如同',
         '哩個',
         '哪個',
         '倘然',
         '例如',
         '各',
         '大力',
         'ltd',
         '她是',
         'respectively',
         '多少',
         'low',
         'goes',
         '再其次',
         '有關',
         '然后',
         'while',
         '從小',
         '另一方面',
         'twice',
         '怎',
         'containing',
         'know',
         "shes",
         '都',
         '噯',
         '誰知',
         '採訪時',
         '＋ξ',
         'want',
         'was',
         '呃',
         'himself',
         '精光',
         'fairly',
         '竟然',
         'except',
         '若',
         'with',
         '不少',
         'despite',
         '與否',
         '作為',
         '它',
         '多年來',
         '何苦',
         'after',
         '全部',
         '>>',
         'says',
         '主要',
         '為著',
         '『',
         '本人',
         '以為',
         'meantime',
         '咪',
         '部分',
         '～＋',
         '邊個',
         'have',
         '一些',
         '替代',
         '縱然',
         '長話短說',
         '［②⑥］',
         '稱',
         '與',
         '來講',
         'really',
         '忽地',
         'believe',
         "didnt",
         '|',
         '正是',
         '何妨',
         '長此下去',
         '從嚴',
         '盡可能',
         '［②',
         'liked',
         '個別',
         '［①ｆ］',
         '｛',
         '不得了',
         '就是說',
         '要不然',
         '繼續',
         '%',
         '這種',
         '巨大',
         '乘勝',
         '猶且',
         '：',
         '很多',
         '每年',
         '那樣',
         '它們的',
         '每天',
         '比及',
         '但凡',
         '引起',
         '有及',
         '飽',
         '採訪',
         'com',
         '挨門逐戶',
         '連日',
         '孰料',
         'throughout',
         '趁早',
         '始而',
         '鞏固',
         '多多少少',
         '比如',
         '嗚',
         'alone',
         '今天',
         '以便',
         '［①ｏ］',
         'qv',
         'described',
         '、',
         'ａ］',
         '此間',
         '致',
         'usually',
         '另悉',
         '根本',
         '趁',
         '它的',
         'various',
         '`',
         'fifth',
         'she',
         'provided',
         '或者',
         'dare',
         'several',
         '何時',
         '奮勇',
         '而言',
         '阿',
         '不定',
         '別是',
         '得了',
         '點解',
         '》',
         '再次',
         '那個',
         'likely',
         '前后',
         '前面',
         '較比',
         '於是',
         '比如說',
         'Ｒ．Ｌ．',
         '旁人',
         '等到',
         'gotten',
         'at',
         '設或',
         '趕',
         'likewise',
         '倘',
         '［②Ｇ］',
         '后者',
         '老是',
         'most',
         '這次',
         '怎麼',
         '這樣',
         '［②⑤］',
         '爾等',
         'abroad',
         '則',
         "ill",
         '論說',
         '據稱',
         '^',
         'given',
         '且',
         '豈非',
         '幫助',
         '極其',
         '不外',
         '一則通過',
         'nothing',
         '彼時',
         '近來',
         '哪',
         'things',
         '哈哈',
         '遵照',
         '賊死',
         '3日',
         "youve",
         '…',
         '誠然',
         '著呢',
         'also',
         '切勿',
         '歸根結底',
         '這些',
         '忽然',
         '蠻',
         '嗰度',
         'whether',
         '截然',
         '最',
         '這點',
         '／',
         '［②Ｂ］',
         '話',
         'under',
         '［③ｇ］',
         '先后',
         '不曾',
         'they',
         '剛好',
         '［③］',
         '粗',
         '非特',
         '並非',
         '不外乎',
         '看樣子',
         '巴',
         '當然',
         '用來',
         '如是',
         '有冇',
         '成日',
         '並無',
         '別管',
         'uses',
         'since',
         '大批',
         '［②③］',
         'a',
         '交口',
         '正巧',
         '｜',
         'lately',
         '否則',
         '行為',
         '互',
         '喏',
         '獨自',
         '允許',
         "ts",
         '一天',
         '卻',
         '年復一年',
         '因為',
         '隻消',
         'Ａ',
         '但係',
         '舉行',
         '那裡',
         '/',
         '不起',
         '遭到',
         'latterly',
         '從此以后',
         '》），',
         '1日',
         '可以',
         '照著',
         '何況',
         'where',
         '隻有',
         '按',
         '一直',
         '趁勢',
         '那麼樣',
         '有利',
         'opposite',
         'beyond',
         '５：０',
         "wont",
         '啷當',
         '維持',
         '實現',
         '＃',
         'inside',
         'backwards',
         '莫不然',
         'indicate',
         '必然',
         '每時每刻',
         '譬如',
         '喺',
         '人哋',
         '［①①］',
         '許多',
         '五',
         '單',
         'you',
         '達旦',
         'way',
         'eg',
         'downwards',
         '你哋',
         '不但...而且',
         'yet',
         'm',
         '逢',
         '寧肯',
         '一次',
         '若是',
         '各式',
         '或許',
         '已經',
         'over',
         '呵呵',
         'consider',
         '頃',
         'provides',
         '順著',
         '假如',
         'thirty',
         '［①Ｂ］',
         '隔日',
         '任',
         '最大',
         '喎',
         '倘使',
         'plus',
         '任務',
         'noone',
         '普遍',
         '且不說',
         '以',
         '那末',
         '后來',
         '不至於',
         'thing',
         '過去',
         'or',
         'upon',
         'certain',
         '如前所述',
         '9',
         '第',
         '他的',
         '到目前為止',
         '日復一日',
         '不僅...而且',
         'placed',
         '好在',
         '僅僅',
         'example',
         'needs',
         'having',
         '立馬',
         '想',
         '何止',
         '倒是',
         "dont",
         '從新',
         '然之後',
         'theres',
         '扑通',
         '儻然',
         '並',
         '所有',
         '［③ｃ］',
         'edu',
         '具體地說',
         'lower',
         '乘隙',
         '最后',
         'such',
         'everyone',
         '不下',
         '幾',
         '＄',
         '汝',
         '相等',
         '一樣',
         '屢',
         "thereve",
         'somewhere',
         'amidst',
         '日見',
         '賴以',
         'moreover',
         '九',
         'y',
         '︿',
         '類如',
         'o',
         '＜',
         '開展',
         '一邊',
         '5',
         '管',
         'out',
         '繼後',
         '不限',
         'ahead',
         '大致',
         'happens',
         "isnt",
         '怎麼辦',
         '不變',
         '將',
         '達到',
         '挨著',
         '他',
         '各自',
         '真係',
         '表明',
         'co',
         'tends',
         '極力',
         '何以',
         '自各兒',
         '范圍',
         "neednt",
         '反過來',
         '默默地',
         '挨家挨戶',
         '也就是說',
         'meanwhile',
         '自后',
         '當真',
         'now',
         '下',
         '(',
         '不得已',
         '人們',
         '看來',
         '有的',
         'past',
         '［②ｃ］',
         '特別是',
         '覺得',
         '非得',
         '一方面',
         'farther',
         '[',
         'thats',
         'specifying',
         '反手',
         '啊呀',
         '咋',
         'thoroughly',
         '數/',
         '挨個',
         '待',
         "mustnt",
         '兒',
         '進來',
         'zero',
         'herein',
         '，也',
         '即或',
         '全面',
         '［②ｄ］',
         '促進',
         '凝神',
         '由此',
         '它們',
         '』',
         '我哋',
         '其二',
         'last',
         '［②⑦］',
         'etc',
         '並不',
         '來說',
         '上述',
         'towards',
         '牢牢',
         'is',
         '即係',
         '離',
         '縷縷',
         'mr',
         '不一',
         '［－',
         '如其',
         '單單',
         '成心',
         '來',
         '因而',
         'whence',
         "hes",
         '再',
         'both',
         '簡直',
         '戰斗',
         '嘎嘎',
         "mightnt",
         '某某',
         '隨后',
         '順',
         '聯袂',
         's',
         '另方面',
         "wouldnt",
         '從今以后',
         'forever',
         '凡是',
         '叮咚',
         'being',
         '分期',
         '正在',
         '路經',
         '爾爾',
         "oughtnt",
         'something',
         '知道',
         'above',
         '曾經',
         '］',
         '通常',
         'half',
         '吶',
         '突然',
         'value',
         '多多益善',
         '單純',
         '縱令',
         'up',
         '出去',
         'ok',
         'should',
         '急匆匆',
         '立刻',
         '罷了',
         'sent',
         '幾經',
         '不妨',
         '後者',
         '處理',
         '即將',
         'recent',
         'nearly',
         'e',
         '各位',
         'directly',
         '［②ｇ］',
         '而外',
         'awfully',
         'followed',
         '您是',
         "there'd",
         '另一個',
         '猶自',
         '當時',
         '逐漸',
         '［⑥］',
         "as",
         '隻當',
         '現代',
         '自後',
         '及',
         '當兒',
         '點',
         '［②ｊ］',
         '此次',
         "he'd",
         '前進',
         'second',
         '甚且',
         '怪',
         '連連',
         '使',
         '理當',
         ']',
         '夠瞧的',
         '於',
         '雲雲',
         '大面兒上',
         'go',
         '佢哋',
         '齊',
         '較之',
         '根據',
         'there',
         'whenever',
         '如次',
         'unless',
         '＜Δ',
         '［］',
         '不日',
         '幾時',
         'tell',
         '大不了',
         '能否',
         '總之',
         '＊',
         "thats",
         'five',
         '八',
         '還要',
         '大多',
         '＞',
         '［④］',
         '行動',
         'ｂ］',
         '企業',
         '其',
         '一切',
         '［②ｅ］',
         '略加',
         '盡然',
         'consequently',
         '儘管',
         'hers',
         'available',
         '以故',
         '這邊',
         'presumably',
         '那邊',
         '要求',
         'going',
         '極了',
         'whilst',
         '也罷',
         '假若',
         '處處',
         '毋寧',
         '滿',
         'and',
         '而是',
         '以后',
         '不可',
         '莫非',
         '恍然',
         '當地',
         '共同',
         '大概',
         '。',
         '大大',
         '甚至於',
         '依據',
         'therein',
         '和',
         '當即',
         '所以',
         '＝｛',
         'seems',
         '較',
         'third',
         '同時',
         '已',
         '隻',
         '怕',
         '惟其',
         '不久',
         '那會兒',
         '2',
         '！',
         '嚴格',
         '我是',
         '矣',
         '從古到今',
         '切莫',
         '［⑤ｆ］',
         'whom',
         '那',
         '恰恰相反',
         '局外',
         'again',
         'sure',
         '碰巧',
         'him',
         '純粹',
         'normally',
         '及其',
         '來不及',
         '連日來',
         'hardly',
         '前後',
         '｝＞',
         '不僅',
         '不怕',
         '略微',
         '自',
         '有的是',
         'outside',
         'can',
         '可是',
         '比方',
         '幾乎',
         '殆',
         '毫無例外',
         '［①］',
         '這會兒',
         'allows',
         '假使',
         '總的說來',
         '諸',
         '率然',
         '只是',
         '再說',
         '［③ｅ］',
         '以外',
         '全年',
         '具有',
         'them',
         '其實',
         '公司',
         '盡如人意',
         'far',
         '咩',
         'into',
         '［①⑥］',
         '風雨無阻',
         '有力',
         '＜±',
         'he',
         '絕',
         '那些',
         '獨',
         '在',
         '傳出',
         '萬一',
         '0日',
         '甚至',
         '重要',
         '何',
         '兼之',
         '白',
         '不時',
         'besides',
         '如',
         'saw',
         '敢於',
         '）、',
         '當頭',
         '少數',
         '［⑤ｄ］',
         'the',
         'two',
         '＝（',
         '失去',
         '具體說來',
         '竟',
         '這時',
         '】',
         '成為',
         '十分',
         '有啲',
         '不特',
         '把',
         '俺',
         '全都',
         'ones',
         '毫無',
         'became',
         '有著',
         'sup',
         '整個',
         '但',
         '就要',
         '．',
         '以免',
         '你',
         '［③ｂ］',
         'anyways',
         '哎呀',
         '考慮',
         '此',
         '喀',
         '地',
         'anyway',
         '完全',
         'able',
         '好象',
         'others',
         '恰似',
         'whatever',
         '您們',
         '馬上',
         '白白',
         '若果',
         '就是了',
         "wholl",
         'from',
         '定',
         '雖說',
         '以上',
         '為主',
         'seem',
         '之後',
         '均',
         'concerning',
         '［⑤ａ］',
         'more',
         '什麼樣',
         '決不',
         '其余',
         'anyone',
         '嗰個',
         '臨到',
         '先生',
         '〉',
         '梆',
         'less',
         '頃刻間',
         '半',
         '咱們',
         '誰料',
         '唯有',
         '然',
         '——',
         '反而',
         '因此',
         '嚴重',
         '［①ｅ］',
         'round',
         '不同',
         'me',
         '［②①］',
         '吧',
         '果然',
         '難說',
         '恰好',
         'eight',
         'underneath',
         "cs",
         "theyll",
         '進入',
         '公然',
         'caption',
         "cant",
         'immediate',
         'seemed',
         '純',
         '最後',
         '切',
         'before',
         'come',
         'any',
         '有',
         '上升',
         '［⑤ｂ］',
         '又',
         '即刻',
         '屆時',
         '主張',
         'does',
         'via',
         '到頭',
         '略',
         '!',
         '因',
         'certainly',
         '此處',
         '與其說',
         '企圖',
         '普通',
         '；',
         '七',
         '那時',
         '從中',
         'never',
         'so',
         '究竟',
         '經過',
         '［②ｂ］',
         '［②ｈ］',
         '是否',
         'are',
         'sensible',
         '則甚',
         '憤然',
         'inasmuch',
         'wherein',
         '喲',
         '暗地裡',
         '常常',
         '&',
         '這麼',
         'just',
         '［③⑩］',
         '正值',
         '而家',
         '沒奈何',
         '專門',
         'take',
         '如今',
         '嘿嘿',
         'i',
         'unlikely',
         'whereupon',
         '沖',
         "it's",
         '還',
         '但願',
         '吖',
         '默然',
         '＜φ',
         'somehow',
         '朝',
         '相對而言',
         '近幾年來',
         'help',
         '從古至今',
         "weve",
         '是以',
         'new',
         '豐富',
         '按理',
         "whod",
         'hi',
         'ninety',
         '雖然',
         '＠',
         '必將',
         '謹',
         'across',
         "shouldnt",
         '除非',
         'probably',
         'someday',
         'look',
         '-',
         '有效',
         'ago',
         '還是',
         '甭',
         "hadnt",
         'oh',
         '分頭',
         '先後',
         '隨後',
         '～',
         '［①ｇ］',
         '其他',
         '它是',
         '不然',
         '自己',
         '咚',
         '連袂',
         '只限',
         '哪些',
         '結合',
         '嘻',
         '奇',
         '$',
         '進行',
         '８',
         '歸根到底',
         'myself',
         '要不',
         '３',
         '背地裡',
         '她們',
         '設使',
         '１',
         '中國',
         '似乎',
         '爾',
         '方能',
         '三番五次',
         '就此',
         '認識',
         '更',
         '難道',
         '只要',
         '所謂',
         '甫',
         '有所',
         '不然的話',
         'could',
         'versus',
         '很',
         '以致',
         '向',
         '他是',
         'came',
         'serious',
         '前此',
         '我們',
         '方',
         '云云',
         'little',
         '2日',
         '而況',
         '自個兒',
         '大多數',
         '除外',
         '~',
         'of',
         '代替',
         '上下',
         '先不先',
         '偶而',
         '［①⑦］',
         '竊',
         '累年',
         '陳年',
         '趁機',
         '騰',
         '集中',
         "id",
         '一般',
         '無論',
         '為止',
         '據此',
         '毫不',
         '每個',
         '［①ｉ］',
         'whereby',
         '某個',
         '從無到有',
         '日益',
         'regardless',
         'that',
         '噉樣',
         '大約',
         'amid',
         '此地',
         '每',
         '唔係',
         '等等',
         '極',
         '［②⑧］',
         '啦',
         '運用',
         '這麼點兒',
         '大都',
         'thank',
         '處在',
         '［①③］',
         '除此',
         '動不動',
         'somebody',
         ':',
         'miss',
         '吱',
         '諸位',
         "theyd",
         '今后',
         '〔',
         '向使',
         '顯然',
         '有點',
         'forward',
         "we'll",
         '川流不息',
         'whose',
         '從速',
         '對於',
         '設立',
         '立時',
         '［④ｄ］',
         '全體',
         'hereupon',
         '不料',
         '啥',
         '二',
         'vs',
         "whatll",
         '的',
         '既...又',
         '不可開交',
         'particularly',
         '也是',
         '恰逢',
         '該',
         "arent",
         '彼此',
         '極大',
         'yourself',
         '憑借',
         '［⑦］',
         '再者說',
         "hasnt",
         '其一',
         '3',
         '表示',
         '人家',
         '一轉眼',
         '除',
         'beforehand',
         'too',
         '基本上',
         '社會主義',
         '互相',
         '怎樣',
         '不獨',
         '背靠背',
         '何處',
         'few',
         '倍感',
         '...',
         '三',
         'against',
         '緊接著',
         '而已',
         '就',
         '傳說',
         '趁便',
         'hence',
         '何必',
         '當中',
         '本身',
         'your',
         '三番兩次',
         '活',
         '極度',
         '恐怕',
         '年',
         '豈',
         '簡而言之',
         'why',
         '仍舊',
         'need',
         '一時',
         '帶',
         '移動',
         '本著',
         '縱',
         '中',
         '練習',
         '［',
         '八成',
         '長線',
         '明確',
         '知',
         '綜上所述',
         '再有',
         '加以',
         '連聲',
         '喺度',
         'saying',
         '何樂而不為',
         '［⑨］',
         '完成',
         '連同',
         '從事',
         '最好',
         'around',
         '這麼樣',
         'seriously',
         '起見',
         '起先',
         'wish',
         'hereafter',
         '分別',
         'on',
         '怪不得',
         '滿足',
         'however',
         '既然',
         '就地',
         'our',
         '保管',
         '看見',
         'whomever',
         '各種',
         'perhaps',
         '大體',
         '僅',
         '轉動',
         '呵',
         '哼',
         '故而',
         '不但',
         '她的',
         '不止',
         '大抵',
         '更為',
         '諸如',
         '親口',
         '得出',
         '當口兒',
         '正常',
         '認真',
         '９',
         'obviously',
         'okay',
         '太',
         '絕頂',
         '理該',
         '長期以來',
         '＜λ',
         '7',
         '較為',
         'if',
         '今年',
         '非但',
         '所',
         '乜嘢',
         'but',
         '隔夜',
         '％',
         '只當',
         'name',
         '保險',
         'thanks',
         '固然',
         'viz',
         '遲早',
         '相似',
         '毫無保留地',
         'her',
         '不止一次',
         '5日',
         'anyhow',
         'neverless',
         '往',
         'taken',
         "whatve",
         '不對',
         '必須',
         '大體上',
         '我',
         '或曰',
         '似的',
         '與其',
         '同',
         '相反',
         'welcome',
         'eighty',
         'specify',
         '不勝',
         '有些',
         'apart',
         '乃至',
         'causes',
         'cant',
         '這裡',
         'near',
         '好的',
         '固',
         '明顯',
         "itd",
         '差不多',
         '＇',
         '［①ｈ］',
         'inner',
         '便於',
         'it',
         'none',
         'else',
         'would',
         '具體',
         'next',
         'follows',
         '勃然',
         '陡然',
         '一',
         '仍',
         '不單',
         '率爾',
         '乘',
         'ｅ］',
         '\ufeff\ufeff、',
         'much',
         '不力',
         '然則',
         '策略地',
         '趁熱',
         'specified',
         '@',
         '如何',
         '即令',
         '咁',
         '當庭',
         '常言說得好',
         '像',
         '莫若',
         '）',
         'ask',
         '共',
         '反倒是',
         '［①Ｄ］',
         '差一點',
         '除此之外',
         '彈指之間',
         '個',
         '·',
         'who',
         'k',
         '爾后',
         '要不是',
         '間或',
         '強烈',
         '從未',
         'ｎｇ昉',
         '經',
         '三天兩頭',
         '高興',
         'seeming',
         '爭取',
         'well',
         'mrs',
         '喂',
         '據說',
         '不隻',
         "couldnt",
         'sub',
         '開立的',
         '不能',
         '深入',
         '＝［',
         'will',
         't',
         '哪怕',
         '這就是說',
         '近',
         '重新',
         '啊哈',
         '盡量',
         'all',
         '其次',
         '前者',
         '並肩',
         '儘管如此',
         '<',
         'contain',
         '不經意',
         '千萬千萬',
         '隨',
         '跟住',
         'maybe',
         '一來',
         'am',
         '顯著',
         '一致',
         '開外',
         '后面',
         '來得及',
         'together',
         'fewer',
         'former',
         '\ufeff人民',
         '如題',
         '呢個',
         '無啦啦',
         '都是',
         '明明',
         '我要',
         '嘅嘢',
         '先',
         '但當',
         '我係',
         '遲啲',
         '搵鬼用',
         '令',
         '就係',
         '無奈',
         '説',
         '什麼都',
         '裏面',
         '做不了',
         '野',
         '開頭',
         '仲',
         '今日',
         '請',
         '做啦',
         '嚟',
         '經常出現',
         '情況',
         '同我講',
         '又係',
         '洗',
         '乜用',
         '洗乜用',
         '但有',
         '作招',
         '徠',
         '超',
         '的人',
         '蚊同',
         '蚊',
         '唔存在',
         '唔滿足',
         '一齊',
         '次次',
         '嗰陣',
         '又要',
         '直頭',
         '簡直',
         '係',
         '先可',
         '根本',
         '就是',
         '說',
         '幹什麼',
         '咁樣',
         '應有',
         '先前',
         '謝謝',
         '想點',
         '日日',
         '超级',
         '一个',
         '直說',
         '沒有',
         '我沒',
         '但系',
         '我用',
         '仲系',
         '唔該',
         '可唔可以',
         '泥個',
         '痴線',
        '好憨鳩',
        '支那人',
        '支那',
        '其身不正',
        '扑街',
        '共產黨',
        '呢啲',
        '港猪',
        '班港',
        '猪',
        '係咪',
        '好似'},
}
STOPWORDS = freeze(_STOPWORDS)
#    'zh':{'人民',
#         '啊',
#         '阿',
#         '哎',
#         '哎呀',
#         '哎喲',
#         '唉',
#         '俺',
#         '俺們',
#         '按',
#         '按照',
#         '吧',
#         '吧噠',
#         '把',
#         '罷了',
#         '被',
#         '本',
#         '本著',
#         '比',
#         '比方',
#         '比如',
#         '鄙人',
#         '彼',
#         '彼此',
#         '邊',
#         '別',
#         '別的',
#         '別說',
#         '並',
#         '並且',
#         '不比',
#         '不成',
#         '不單',
#         '不但',
#         '不獨',
#         '不管',
#         '不光',
#         '不過',
#         '不僅',
#         '不拘',
#         '不論',
#         '不怕',
#         '不然',
#         '不如',
#         '不特',
#         '不惟',
#         '不問',
#         '不隻',
#         '朝',
#         '朝著',
#         '趁',
#         '趁著',
#         '乘',
#         '沖',
#         '除',
#         '除此之外',
#         '除非',
#         '除了',
#         '此',
#         '此間',
#         '此外',
#         '從',
#         '從而',
#         '打',
#         '待',
#         '但',
#         '但是',
#         '當',
#         '當著',
#         '到',
#         '得',
#         '的',
#         '的話',
#         '等',
#         '等等',
#         '地',
#         '第',
#         '叮咚',
#         '對',
#         '對於',
#         '多',
#         '多少',
#         '而',
#         '而況',
#         '而且',
#         '而是',
#         '而外',
#         '而言',
#         '而已',
#         '爾后',
#         '反過來',
#         '反過來說',
#         '反之',
#         '非但',
#         '非徒',
#         '否則',
#         '嘎',
#         '嘎登',
#         '該',
#         '趕',
#         '個',
#         '各',
#         '各個',
#         '各位',
#         '各種',
#         '各自',
#         '給',
#         '根據',
#         '跟',
#         '故',
#         '故此',
#         '固然',
#         '關於',
#         '管',
#         '歸',
#         '果然',
#         '果真',
#         '過',
#         '哈',
#         '哈哈',
#         '呵',
#         '和',
#         '何',
#         '何處',
#         '何況',
#         '何時',
#         '嘿',
#         '哼',
#         '哼唷',
#         '呼哧',
#         '乎',
#         '嘩',
#         '還是',
#         '還有',
#         '換句話說',
#         '換言之',
#         '或',
#         '或是',
#         '或者',
#         '極了',
#         '及',
#         '及其',
#         '及至',
#         '即',
#         '即便',
#         '即或',
#         '即令',
#         '即若',
#         '即使',
#         '幾',
#         '幾時',
#         '己',
#         '既',
#         '既然',
#         '既是',
#         '繼而',
#         '加之',
#         '假如',
#         '假若',
#         '假使',
#         '鑒於',
#         '將',
#         '較',
#         '較之',
#         '叫',
#         '接著',
#         '結果',
#         '借',
#         '緊接著',
#         '進而',
#         '盡',
#         '盡管',
#         '經',
#         '經過',
#         '就',
#         '就是',
#         '就是說',
#         '據',
#         '具體地說',
#         '具體說來',
#         '開始',
#         '開外',
#         '靠',
#         '咳',
#         '可',
#         '可見',
#         '可是',
#         '可以',
#         '況且',
#         '啦',
#         '來',
#         '來著',
#         '離',
#         '例如',
#         '哩',
#         '連',
#         '連同',
#         '兩者',
#         '了',
#         '臨',
#         '另',
#         '另外',
#         '另一方面',
#         '論',
#         '嘛',
#         '嗎',
#         '慢說',
#         '漫說',
#         '冒',
#         '麼',
#         '每',
#         '每當',
#         '們',
#         '莫若',
#         '某',
#         '某個',
#         '某些',
#         '拿',
#         '哪',
#         '哪邊',
#         '哪兒',
#         '哪個',
#         '哪裡',
#         '哪年',
#         '哪怕',
#         '哪天',
#         '哪些',
#         '哪樣',
#         '那',
#         '那邊',
#         '那兒',
#         '那個',
#         '那會兒',
#         '那裡',
#         '那麼',
#         '那麼些',
#         '那麼樣',
#         '那時',
#         '那些',
#         '那樣',
#         '乃',
#         '乃至',
#         '呢',
#         '能',
#         '你',
#         '你們',
#         '您',
#         '寧',
#         '寧可',
#         '寧肯',
#         '寧願',
#         '哦',
#         '嘔',
#         '啪達',
#         '旁人',
#         '呸',
#         '憑',
#         '憑借',
#         '其',
#         '其次',
#         '其二',
#         '其他',
#         '其它',
#         '其一',
#         '其余',
#         '其中',
#         '起',
#         '起見',
#         '豈但',
#         '恰恰相反',
#         '前后',
#         '前者',
#         '且',
#         '然而',
#         '然后',
#         '然則',
#         '讓',
#         '人家',
#         '任',
#         '任何',
#         '任憑',
#         '如',
#         '如此',
#         '如果',
#         '如何',
#         '如其',
#         '如若',
#         '如上所述',
#         '若',
#         '若非',
#         '若是',
#         '啥',
#         '上下',
#         '尚且',
#         '設若',
#         '設使',
#         '甚而',
#         '甚麼',
#         '甚至',
#         '省得',
#         '時候',
#         '什麼',
#         '什麼樣',
#         '使得',
#         '是',
#         '是的',
#         '首先',
#         '誰',
#         '誰知',
#         '順',
#         '順著',
#         '似的',
#         '雖',
#         '雖然',
#         '雖說',
#         '雖則',
#         '隨',
#         '隨著',
#         '所',
#         '所以',
#         '他',
#         '他們',
#         '他人',
#         '它',
#         '它們',
#         '她',
#         '她們',
#         '倘',
#         '倘或',
#         '倘然',
#         '倘若',
#         '倘使',
#         '騰',
#         '替',
#         '通過',
#         '同',
#         '同時',
#         '哇',
#         '萬一',
#         '往',
#         '望',
#         '為',
#         '為何',
#         '為了',
#         '為什麼',
#         '為著',
#         '喂',
#         '嗡嗡',
#         '我',
#         '我們',
#         '嗚',
#         '嗚呼',
#         '烏乎',
#         '無論',
#         '無寧',
#         '毋寧',
#         '嘻',
#         '嚇',
#         '相對而言',
#         '像',
#         '向',
#         '向著',
#         '噓',
#         '呀',
#         '焉',
#         '沿',
#         '沿著',
#         '要',
#         '要不',
#         '要不然',
#         '要不是',
#         '要麼',
#         '要是',
#         '也',
#         '也罷',
#         '也好',
#         '一',
#         '一般',
#         '一旦',
#         '一方面',
#         '一來',
#         '一切',
#         '一樣',
#         '一則',
#         '依',
#         '依照',
#         '矣',
#         '以',
#         '以便',
#         '以及',
#         '以免',
#         '以至',
#         '以至於',
#         '以致',
#         '抑或',
#         '因',
#         '因此',
#         '因而',
#         '因為',
#         '喲',
#         '用',
#         '由',
#         '由此可見',
#         '由於',
#         '有',
#         '有的',
#         '有關',
#         '有些',
#         '又',
#         '於',
#         '於是',
#         '於是乎',
#         '與',
#         '與此同時',
#         '與否',
#         '與其',
#         '越是',
#         '雲雲',
#         '哉',
#         '再說',
#         '再者',
#         '在',
#         '在下',
#         '咱',
#         '咱們',
#         '則',
#         '怎',
#         '怎麼',
#         '怎麼辦',
#         '怎麼樣',
#         '怎樣',
#         '咋',
#         '照',
#         '照著',
#         '者',
#         '這',
#         '這邊',
#         '這兒',
#         '這個',
#         '這會兒',
#         '這就是說',
#         '這裡',
#         '這麼',
#         '這麼點兒',
#         '這麼些',
#         '這麼樣',
#         '這時',
#         '這些',
#         '這樣',
#         '正如',
#         '吱',
#         '之',
#         '之類',
#         '之所以',
#         '之一',
#         '隻是',
#         '隻限',
#         '隻要',
#         '隻有',
#         '至',
#         '至於',
#         '諸位',
#         '著',
#         '著呢',
#         '自',
#         '自從',
#         '自個兒',
#         '自各兒',
#         '自己',
#         '自家',
#         '自身',
#         '綜上所述',
#         '總的來看',
#         '總的來說',
#         '總的說來',
#         '總而言之',
#         '總之',
#         '縱',
#         '縱令',
#         '縱然',
#         '縱使',
#         '遵照',
#         '作為',
#         '兮',
#         '呃',
#         '唄',
#         '咚',
#         '咦',
#         '喏',
#         '啐',
#         '喔唷',
#         '嗬',
#         '嗯',
#         '噯',
#         '~',
#         '!',
#         '.',
#         ':',
#         '"',
#         "'",
#         '(',
#         ')',
#         '*',
#         'A',
#         '白',
#         '社會主義',
#         '--',
#         '..',
#         '>>',
#         ' [',
#         ' ]',
#         '',
#         '<',
#         '>',
#         '/',
#         '\\',
#         '|',
#         '-',
#         '_',
#         '+',
#         '=',
#         '&',
#         '^',
#         '%',
#         '#',
#         '@',
#         '`',
#         ';',
#         '$',
#         '（',
#         '）',
#         '——',
#         '—',
#         '￥',
#         '·',
#         '...',
#         '‘',
#         '’',
#         '〉',
#         '〈',
#         '…',
#         '\u3000',
#         '0',
#         '1',
#         '2',
#         '3',
#         '4',
#         '5',
#         '6',
#         '7',
#         '8',
#         '9',
#         '０',
#         '１',
#         '２',
#         '３',
#         '４',
#         '５',
#         '６',
#         '７',
#         '８',
#         '９',
#         '二',
#         '三',
#         '四',
#         '五',
#         '六',
#         '七',
#         '八',
#         '九',
#         '零',
#         '＞',
#         '＜',
#         '＠',
#         '＃',
#         '＄',
#         '％',
#         '︿',
#         '＆',
#         '＊',
#         '＋',
#         '～',
#         '｜',
#         '［',
#         '］',
#         '｛',
#         '｝',
#         '啊哈',
#         '啊呀',
#         '啊喲',
#         '挨次',
#         '挨個',
#         '挨家挨戶',
#         '挨門挨戶',
#         '挨門逐戶',
#         '挨著',
#         '按理',
#         '按期',
#         '按時',
#         '按說',
#         '暗地裡',
#         '暗中',
#         '暗自',
#         '昂然',
#         '八成',
#         '白白',
#         '半',
#         '梆',
#         '保管',
#         '保險',
#         '飽',
#         '背地裡',
#         '背靠背',
#         '倍感',
#         '倍加',
#         '本人',
#         '本身',
#         '甭',
#         '比起',
#         '比如說',
#         '比照',
#         '畢竟',
#         '必',
#         '必定',
#         '必將',
#         '必須',
#         '便',
#         '別人',
#         '並非',
#         '並肩',
#         '並沒',
#         '並沒有',
#         '並排',
#         '並無',
#         '勃然',
#         '不',
#         '不必',
#         '不常',
#         '不大',
#         '不但...而且',
#         '不得',
#         '不得不',
#         '不得了',
#         '不得已',
#         '不迭',
#         '不定',
#         '不對',
#         '不妨',
#         '不管怎樣',
#         '不會',
#         '不僅...而且',
#         '不僅僅',
#         '不僅僅是',
#         '不經意',
#         '不可開交',
#         '不可抗拒',
#         '不力',
#         '不了',
#         '不料',
#         '不滿',
#         '不免',
#         '不能不',
#         '不起',
#         '不巧',
#         '不然的話',
#         '不日',
#         '不少',
#         '不勝',
#         '不時',
#         '不是',
#         '不同',
#         '不能',
#         '不要',
#         '不外',
#         '不外乎',
#         '不下',
#         '不限',
#         '不消',
#         '不已',
#         '不亦樂乎',
#         '不由得',
#         '不再',
#         '不擇手段',
#         '不怎麼',
#         '不曾',
#         '不知不覺',
#         '不止',
#         '不止一次',
#         '不至於',
#         '才',
#         '才能',
#         '策略地',
#         '差不多',
#         '差一點',
#         '常',
#         '常常',
#         '常言道',
#         '常言說',
#         '常言說得好',
#         '長此下去',
#         '長話短說',
#         '長期以來',
#         '長線',
#         '敞開兒',
#         '徹夜',
#         '陳年',
#         '趁便',
#         '趁機',
#         '趁熱',
#         '趁勢',
#         '趁早',
#         '成年',
#         '成年累月',
#         '成心',
#         '乘機',
#         '乘勝',
#         '乘勢',
#         '乘隙',
#         '乘虛',
#         '誠然',
#         '遲早',
#         '充分',
#         '充其極',
#         '充其量',
#         '抽冷子',
#         '臭',
#         '初',
#         '出',
#         '出來',
#         '出去',
#         '除此',
#         '除此而外',
#         '除此以外',
#         '除開',
#         '除去',
#         '除卻',
#         '除外',
#         '處處',
#         '川流不息',
#         '傳',
#         '傳說',
#         '傳聞',
#         '串行',
#         '純',
#         '純粹',
#         '此后',
#         '此中',
#         '次第',
#         '匆匆',
#         '從不',
#         '從此',
#         '從此以后',
#         '從古到今',
#         '從古至今',
#         '從今以后',
#         '從寬',
#         '從來',
#         '從輕',
#         '從速',
#         '從頭',
#         '從未',
#         '從無到有',
#         '從小',
#         '從新',
#         '從嚴',
#         '從優',
#         '從早到晚',
#         '從中',
#         '從重',
#         '湊巧',
#         '粗',
#         '存心',
#         '達旦',
#         '打從',
#         '打開天窗說亮話',
#         '大',
#         '大不了',
#         '大大',
#         '大抵',
#         '大都',
#         '大多',
#         '大凡',
#         '大概',
#         '大家',
#         '大舉',
#         '大略',
#         '大面兒上',
#         '大事',
#         '大體',
#         '大體上',
#         '大約',
#         '大張旗鼓',
#         '大致',
#         '呆呆地',
#         '帶',
#         '殆',
#         '待到',
#         '單',
#         '單純',
#         '單單',
#         '但願',
#         '彈指之間',
#         '當場',
#         '當兒',
#         '當即',
#         '當口兒',
#         '當然',
#         '當庭',
#         '當頭',
#         '當下',
#         '當真',
#         '當中',
#         '倒不如',
#         '倒不如說',
#         '倒是',
#         '到處',
#         '到底',
#         '到了兒',
#         '到目前為止',
#         '到頭',
#         '到頭來',
#         '得起',
#         '得天獨厚',
#         '的確',
#         '等到',
#         '叮當',
#         '頂多',
#         '定',
#         '動不動',
#         '動輒',
#         '陡然',
#         '都',
#         '獨',
#         '獨自',
#         '斷然',
#         '頓時',
#         '多次',
#         '多多',
#         '多多少少',
#         '多多益善',
#         '多虧',
#         '多年來',
#         '多年前',
#         '而后',
#         '而論',
#         '而又',
#         '爾等',
#         '二話不說',
#         '二話沒說',
#         '反倒',
#         '反倒是',
#         '反而',
#         '反手',
#         '反之亦然',
#         '反之則',
#         '方',
#         '方才',
#         '方能',
#         '放量',
#         '非常',
#         '非得',
#         '分期',
#         '分期分批',
#         '分頭',
#         '奮勇',
#         '憤然',
#         '風雨無阻',
#         '逢',
#         '弗',
#         '甫',
#         '嘎嘎',
#         '該當',
#         '概',
#         '趕快',
#         '趕早不趕晚',
#         '敢',
#         '敢情',
#         '敢於',
#         '剛',
#         '剛才',
#         '剛好',
#         '剛巧',
#         '高低',
#         '格外',
#         '隔日',
#         '隔夜',
#         '個人',
#         '各式',
#         '更',
#         '更加',
#         '更進一步',
#         '更為',
#         '公然',
#         '共',
#         '共總',
#         '夠瞧的',
#         '姑且',
#         '古來',
#         '故而',
#         '故意',
#         '固',
#         '怪',
#         '怪不得',
#         '慣常',
#         '光',
#         '光是',
#         '歸根到底',
#         '歸根結底',
#         '過於',
#         '毫不',
#         '毫無',
#         '毫無保留地',
#         '毫無例外',
#         '好在',
#         '何必',
#         '何嘗',
#         '何妨',
#         '何苦',
#         '何樂而不為',
#         '何須',
#         '何止',
#         '很',
#         '很多',
#         '很少',
#         '轟然',
#         '后來',
#         '呼啦',
#         '忽地',
#         '忽然',
#         '互',
#         '互相',
#         '嘩啦',
#         '話說',
#         '還',
#         '恍然',
#         '會',
#         '豁然',
#         '活',
#         '伙同',
#         '或多或少',
#         '或許',
#         '基本',
#         '基本上',
#         '基於',
#         '極',
#         '極大',
#         '極度',
#         '極端',
#         '極力',
#         '極其',
#         '極為',
#         '急匆匆',
#         '即將',
#         '即刻',
#         '即是說',
#         '幾度',
#         '幾番',
#         '幾乎',
#         '幾經',
#         '既...又',
#         '繼之',
#         '加上',
#         '加以',
#         '間或',
#         '簡而言之',
#         '簡言之',
#         '簡直',
#         '見',
#         '將才',
#         '將近',
#         '將要',
#         '交口',
#         '較比',
#         '較為',
#         '接連不斷',
#         '接下來',
#         '皆可',
#         '截然',
#         '截至',
#         '藉以',
#         '借此',
#         '借以',
#         '屆時',
#         '僅',
#         '僅僅',
#         '謹',
#         '進來',
#         '進去',
#         '近',
#         '近幾年來',
#         '近來',
#         '近年來',
#         '盡管如此',
#         '盡可能',
#         '盡快',
#         '盡量',
#         '盡然',
#         '盡如人意',
#         '盡心竭力',
#         '盡心盡力',
#         '盡早',
#         '精光',
#         '經常',
#         '竟',
#         '竟然',
#         '究竟',
#         '就此',
#         '就地',
#         '就算',
#         '居然',
#         '局外',
#         '舉凡',
#         '據稱',
#         '據此',
#         '據實',
#         '據說',
#         '據我所知',
#         '據悉',
#         '具體來說',
#         '決不',
#         '決非',
#         '絕',
#         '絕不',
#         '絕頂',
#         '絕對',
#         '絕非',
#         '均',
#         '喀',
#         '看',
#         '看來',
#         '看起來',
#         '看上去',
#         '看樣子',
#         '可好',
#         '可能',
#         '恐怕',
#         '快',
#         '快要',
#         '來不及',
#         '來得及',
#         '來講',
#         '來看',
#         '攔腰',
#         '牢牢',
#         '老',
#         '老大',
#         '老老實實',
#         '老是',
#         '累次',
#         '累年',
#         '理當',
#         '理該',
#         '理應',
#         '歷',
#         '立',
#         '立地',
#         '立刻',
#         '立馬',
#         '立時',
#         '聯袂',
#         '連連',
#         '連日',
#         '連日來',
#         '連聲',
#         '連袂',
#         '臨到',
#         '另方面',
#         '另行',
#         '另一個',
#         '路經',
#         '屢',
#         '屢次',
#         '屢次三番',
#         '屢屢',
#         '縷縷',
#         '率爾',
#         '率然',
#         '略',
#         '略加',
#         '略微',
#         '略為',
#         '論說',
#         '馬上',
#         '蠻',
#         '滿',
#         '沒',
#         '沒有',
#         '每逢',
#         '每每',
#         '每時每刻',
#         '猛然',
#         '猛然間',
#         '莫',
#         '莫不',
#         '莫非',
#         '莫如',
#         '默默地',
#         '默然',
#         '吶',
#         '那末',
#         '奈',
#         '難道',
#         '難得',
#         '難怪',
#         '難說',
#         '內',
#         '年復一年',
#         '凝神',
#         '偶而',
#         '偶爾',
#         '怕',
#         '砰',
#         '碰巧',
#         '譬如',
#         '偏偏',
#         '乒',
#         '平素',
#         '頗',
#         '迫於',
#         '扑通',
#         '其后',
#         '其實',
#         '奇',
#         '齊',
#         '起初',
#         '起來',
#         '起首',
#         '起頭',
#         '起先',
#         '豈',
#         '豈非',
#         '豈止',
#         '迄',
#         '恰逢',
#         '恰好',
#         '恰恰',
#         '恰巧',
#         '恰如',
#         '恰似',
#         '千',
#         '千萬',
#         '千萬千萬',
#         '切',
#         '切不可',
#         '切莫',
#         '切切',
#         '切勿',
#         '竊',
#         '親口',
#         '親身',
#         '親手',
#         '親眼',
#         '親自',
#         '頃',
#         '頃刻',
#         '頃刻間',
#         '頃刻之間',
#         '請勿',
#         '窮年累月',
#         '取道',
#         '去',
#         '權時',
#         '全都',
#         '全力',
#         '全年',
#         '全然',
#         '全身心',
#         '然',
#         '人人',
#         '仍',
#         '仍舊',
#         '仍然',
#         '日復一日',
#         '日見',
#         '日漸',
#         '日益',
#         '日臻',
#         '如常',
#         '如此等等',
#         '如次',
#         '如今',
#         '如期',
#         '如前所述',
#         '如上',
#         '如下',
#         '汝',
#         '三番兩次',
#         '三番五次',
#         '三天兩頭',
#         '瑟瑟',
#         '沙沙',
#         '上',
#         '上來',
#         '上去',
#         '一個',
#         '月',
#         '日'
#        },
#}

#_STOPWORDS.update({'bs': _STOPWORDS['hr']})








#
#from pyrsistent import freeze
#
#_STOPWORDS = {
#    'en': {
#        'a',
#        "a's",
#        'able',
#        'about',
#        'above',
#        'according',
#        'accordingly',
#        'across',
#        'actually',
#        'after',
#        'afterwards',
#        'again',
#        'against',
#        "ain't",
#        'all',
#        'allow',
#        'allows',
#        'almost',
#        'alone',
#        'along',
#        'already',
#        'also',
#        'although',
#        'always',
#        'am',
#        'among',
#        'amongst',
#        'an',
#        'and',
#        'another',
#        'any',
#        'anybody',
#        'anyhow',
#        'anyone',
#        'anything',
#        'anyway',
#        'anyways',
#        'anywhere',
#        'apart',
#        'appear',
#        'appreciate',
#        'appropriate',
#        'are',
#        "aren't",
#        'around',
#        'as',
#        'aside',
#        'ask',
#        'asking',
#        'associated',
#        'at',
#        'available',
#        'away',
#        'awfully',
#        'b',
#        'be',
#        'became',
#        'because',
#        'become',
#        'becomes',
#        'becoming',
#        'been',
#        'before',
#        'beforehand',
#        'behind',
#        'being',
#        'believe',
#        'below',
#        'beside',
#        'besides',
#        'best',
#        'better',
#        'between',
#        'beyond',
#        'both',
#        'brief',
#        'but',
#        'by',
#        'c',
#        "c'mon",
#        "c's",
#        'came',
#        'can',
#        "can't",
#        'cannot',
#        'cant',
#        'cause',
#        'causes',
#        'certain',
#        'certainly',
#        'changes',
#        'clearly',
#        'co',
#        'com',
#        'come',
#        'comes',
#        'concerning',
#        'consequently',
#        'consider',
#        'considering',
#        'contain',
#        'containing',
#        'contains',
#        'corresponding',
#        'could',
#        "couldn't",
#        'course',
#        'currently',
#        'd',
#        'definitely',
#        'described',
#        'despite',
#        'did',
#        "didn't",
#        'different',
#        'do',
#        'does',
#        "doesn't",
#        'doing',
#        "don't",
#        'done',
#        'down',
#        'downwards',
#        'during',
#        'e',
#        'each',
#        'edu',
#        'eg',
#        'eight',
#        'either',
#        'else',
#        'even',
#        'elsewhere',
#        'enough',
#        'entirely',
#        'especially',
#        'et',
#        'etc',
#        'even',
#        'ever',
#        'every',
#        'everybody',
#        'everyone',
#        'everything',
#        'everywhere',
#        'ex',
#        'exactly',
#        'example',
#        'except',
#        'f',
#        'far',
#        'few',
#        'fifth',
#        'first',
#        'five',
#        'followed',
#        'following',
#        'follows',
#        'for',
#        'former',
#        'formerly',
#        'forth',
#        'four',
#        'from',
#        'further',
#        'furthermore',
#        'g',
#        'get',
#        'gets',
#        'getting',
#        'given',
#        'gives',
#        'go',
#        'goes',
#        'going',
#        'gone',
#        'got',
#        'gotten',
#        'greetings',
#        'h',
#        'had',
#        "hadn't",
#        'happens',
#        'hardly',
#        'has',
#        "hasn't",
#        'have',
#        "haven't",
#        'having',
#        'he',
#        "he's",
#        'hello',
#        'help',
#        'hence',
#        'her',
#        'here',
#        "here's",
#        'hereafter',
#        'hereby',
#        'herein',
#        'hereupon',
#        'hers',
#        'herself',
#        'hi',
#        'him',
#        'himself',
#        'his',
#        'hither',
#        'hopefully',
#        'how',
#        'howbeit',
#        'however',
#        'i',
#        "i'd",
#        "i'll",
#        "i'm",
#        "i've",
#        'ie',
#        'if',
#        'ignored',
#        'immediate',
#        'in',
#        'inasmuch',
#        'inc',
#        'include',
#        'including',
#        'indeed',
#        'indicate',
#        'indicated',
#        'indicates',
#        'inner',
#        'insofar',
#        'instead',
#        'into',
#        'inward',
#        'is',
#        "isn't",
#        'it',
#        "it'd",
#        "it'll",
#        "it's",
#        'its',
#        'itself',
#        'j',
#        'just',
#        'k',
#        'keep',
#        'keeps',
#        'kept',
#        'know',
#        'knows',
#        'known',
#        'l',
#        'last',
#        'lately',
#        'later',
#        'latter',
#        'latterly',
#        'least',
#        'less',
#        'lest',
#        'let',
#        "let's",
#        'like',
#        'liked',
#        'likely',
#        'little',
#        'look',
#        'looking',
#        'looks',
#        'ltd',
#        'm',
#        'mainly',
#        'many',
#        'may',
#        'maybe',
#        'me',
#        'mean',
#        'meanwhile',
#        'merely',
#        'might',
#        'more',
#        'moreover',
#        'most',
#        'mostly',
#        'much',
#        'must',
#        'my',
#        'myself',
#        'n',
#        'name',
#        'namely',
#        'nd',
#        'near',
#        'nearly',
#        'necessary',
#        'need',
#        'needs',
#        'neither',
#        'never',
#        'nevertheless',
#        'new',
#        'next',
#        'nine',
#        'no',
#        'nobody',
#        'non',
#        'none',
#        'noone',
#        'nor',
#        'normally',
#        'not',
#        'nothing',
#        'novel',
#        'now',
#        'nowhere',
#
#        'obviously',
#        'of',
#        'off',
#        'often',
#        'oh',
#        'ok',
#        'okay',
#        'old',
#        'on',
#        'once',
#        'one',
#        'ones',
#        'only',
#        'onto',
#        'or',
#        'other',
#        'others',
#        'otherwise',
#        'ought',
#        'our',
#        'ours',
#        'ourselves',
#        'out',
#        'outside',
#        'over',
#        'overall',
#        'own',
#        'p',
#        'page',
#        'particular',
#        'particularly',
#        'per',
#        'perhaps',
#        'placed',
#        'please',
#        'plus',
#        'possible',
#        'presumably',
#        'probably',
#        'provides',
#        'q',
#        'que',
#        'quite',
#        'qv',
#        'r',
#        'rather',
#        'rd',
#        're',
#        'really',
#        'reasonably',
#        'regarding',
#        'regardless',
#        'regards',
#        'relatively',
#        'respectively',
#        'right',
#        's',
#        'said',
#        'same',
#        'saw',
#        'say',
#        'saying',
#        'says',
#        'second',
#        'secondly',
#        'see',
#        'seeing',
#        'seem',
#        'seemed',
#        'seeming',
#        'seems',
#        'seen',
#        'self',
#        'selves',
#        'sensible',
#        'sent',
#        'serious',
#        'seriously',
#        'seven',
#        'several',
#        'shall',
#        'she',
#        'should',
#        "shouldn't",
#        'since',
#        'six',
#        'so',
#        'some',
#        'somebody',
#        'somehow',
#        'someone',
#        'something',
#        'sometime',
#        'sometimes',
#        'somewhat',
#        'somewhere',
#        'soon',
#        'sorry',
#        'specified',
#        'specify',
#        'specifying',
#        'still',
#        'sub',
#        'such',
#        'sup',
#        'sure',
#        't',
#        "t's",
#        'take',
#        'taken',
#        'tell',
#        'tends',
#        'th',
#        'than',
#        'thank',
#        'thanks',
#        'thanx',
#        'that',
#        "that's",
#        'thats',
#        'the',
#        'their',
#        'theirs',
#        'them',
#        'themselves',
#        'then',
#        'thence',
#        'there',
#        "there's",
#        'thereafter',
#        'thereby',
#        'therefore',
#        'therein',
#        'theres',
#        'thereupon',
#        'these',
#        'they',
#        "they'd",
#        "they'll",
#        "they're",
#        "they've",
#        'think',
#        'third',
#        'this',
#        'thorough',
#        'thoroughly',
#        'those',
#        'though',
#        'three',
#        'through',
#        'throughout',
#        'thru',
#        'thus',
#        'to',
#        'together',
#        'too',
#        'took',
#        'toward',
#        'towards',
#        'tried',
#        'tries',
#        'truly',
#        'try',
#        'trying',
#        'twice',
#        'two',
#        'u',
#        'un',
#        'under',
#        'unfortunately',
#        'unless',
#        'unlikely',
#        'until',
#        'unto',
#        'up',
#        'upon',
#        'us',
#        'use',
#        'used',
#        'useful',
#        'uses',
#        'using',
#        'usually',
#        'uucp',
#        'v',
#        'value',
#        'various',
#        'very',
#        'via',
#        'viz',
#        'vs',
#        'want',
#        'wants',
#        'was',
#        "wasn't",
#        'way',
#        'we',
#        "we'd",
#        "we'll",
#        "we're",
#        "we've",
#        'website',
#        'welcome',
#        'well',
#        'went',
#        'were',
#        "weren't",
#        'what',
#        "what's",
#        'whatever',
#        'when',
#        'whence',
#        'whenever',
#        'where',
#        "where's",
#        'whereafter',
#        'whereas',
#        'whereby',
#        'wherein',
#        'whereupon',
#        'wherever',
#        'whether',
#        'which',
#        'while',
#        'whither',
#        'who',
#        "who's",
#        'whoever',
#        'whole',
#        'whom',
#        'whose',
#        'why',
#        'will',
#        'willing',
#        'wish',
#        'with',
#        'within',
#        'without',
#        "won't",
#        'would',
#        'would',
#        "wouldn't",
#        'x',
#
#        'yes',
#        'yet',
#        'you',
#        "you'd",
#        "you'll",
#        "you're",
#        "you've",
#        'your',
#        'yours',
#        'yourself',
#        'yourselves',
#        'z',
#        'zero',
#        
#        'a',
#         'about',
#         'above',
#         'after',
#         'again',
#         'against',
#         'ain',
#         'all',
#         'am',
#         'an',
#         'and',
#         'any',
#         'are',
#         'aren',
#         'arent',
#         'as',
#         'at',
#         'be',
#         'because',
#         'been',
#         'before',
#         'being',
#         'below',
#         'between',
#         'both',
#         'but',
#         'by',
#         'can',
#         'couldn',
#         'couldnt',
#         'd',
#         'did',
#         'didn',
#         'didnt',
#         'do',
#         'does',
#         'doesn',
#         'doesnt',
#         'doing',
#         'don',
#         'dont',
#         'down',
#         'during',
#         'each',
#         'few',
#         'for',
#         'from',
#         'further',
#         'had',
#         'hadn',
#         'hadnt',
#         'has',
#         'hasn',
#         'hasnt',
#         'have',
#         'haven',
#         'havent',
#         'having',
#         'he',
#         'her',
#         'here',
#         'hers',
#         'herself',
#         'him',
#         'himself',
#         'his',
#         'how',
#         'i',
#         'if',
#         'in',
#         'into',
#         'is',
#         'isn',
#         'isnt',
#         'it',
#         'its',
#         'itself',
#         'just',
#         'll',
#
#         'ma',
#         'me',
#         'mightn',
#         'mightnt',
#         'more',
#         'most',
#         'mustn',
#         'mustnt',
#         'my',
#         'myself',
#         'needn',
#         'neednt',
#         'no',
#         'nor',
#         'not',
#         'now',
#
#         'of',
#         'off',
#         'on',
#         'once',
#         'only',
#         'or',
#         'other',
#         'our',
#         'ours',
#         'ourselves',
#         'out',
#         'over',
#         'own',
#         're',
#         'same',
#         'shan',
#         'shant',
#         'she',
#         'shes',
#         'should',
#         'shouldn',
#         'shouldnt',
#         'shouldve',
#         'so',
#         'some',
#         'such',
#         'than',
#         'that',
#         'thatll',
#         'the',
#         'their',
#         'theirs',
#         'them',
#         'themselves',
#         'then',
#         'there',
#         'these',
#         'they',
#         'this',
#         'those',
#         'through',
#         'to',
#         'too',
#         'under',
#         'until',
#         'up',
#         've',
#         'very',
#         'was',
#         'wasn',
#         'wasnt',
#         'we',
#         'were',
#         'weren',
#         'werent',
#         'what',
#         'when',
#         'where',
#         'which',
#         'while',
#         'who',
#         'whom',
#         'why',
#         'will',
#         'with',
#         'won',
#         'wont',
#         'wouldn',
#         'wouldnt',
#         'you',
#         'youd',
#         'youll',
#         'your',
#         'youre',
#         'yours',
#         'yourself',
#         'yourselves',
#         'youve',
#         "cant", 'cannot', 'fix', 'cant', 'never', 'slow', 'disable', 'unable'
#    },
#}
#
##_STOPWORDS.update({'bs': _STOPWORDS['hr']})
#
#STOPWORDS = freeze(_STOPWORDS)
